### ISSUE TITLE
omsadmin.sh Option Breaking omsagent

### ISSUE THREAD

**Issue by Silent-work** [lancefrench/oms-agent-for-linux-boshrelease#4]
While troubleshooting `omsagent` issues, one of the troubleshooting steps in multiple Microsoft documents suggests to execute `omsadmin.sh -l` to check the status of the agent. This is also executed in other scripts as well to check on the status and to see if it's onboarded/registered.

I found that executing `omsadmin.sh` is causing the `omsagent` to enter a non-stop restart loop, and it's returning that the `omsagent` is not running when it was:

```
mysql/b3f6985d-e4c6-45a8-b592-bfa515ebbeee:~# /opt/microsoft/omsagent/bin/omsadmin.sh -l
Primary Workspace: xxx-xxx-xxx-xxx-xxx    Status: Warning(OMSAgent Registered, Not Running)

mysql/b3f6985d-e4c6-45a8-b592-bfa515ebbeee:~# for i in $(seq 1 5); do cat /var/vcap/sys/run/omsagent/omsagent.pid && echo; sleep 5; done
13292
13452
13452
13615
13615

mysql/b3f6985d-e4c6-45a8-b592-bfa515ebbeee:~# for i in $(seq 1 5); do cat /var/vcap/sys/run/omsagent/omsagent.pid && echo; sleep 5; done
15845
16010
16010
16168
16168
```

**Comment by Silent-work** [comment]
* When you execute `omsadmin.sh -l`, it sets `LIST_WORKSPACES=1`.
* When this is set to `1`, it executes the function `list_workspaces`.
* `list_workspaces` executes `show_workspace_status` for the current workspace detected.
* `show_workspace_status` then executes the `SERVICE_CONTROL` script:

```    
$SERVICE_CONTROL is-running $ws_id
```

* This variable refers to:

```
# Service Control script
SERVICE_CONTROL=/opt/microsoft/omsagent/bin/service_control
```

* This file is a symlink to the `omsagent-ctl` script:

```
mysql/b3f6985d-e4c6-45a8-b592-bfa515ebbeee:~# ls -la /opt/microsoft/omsagent/bin/service_control
lrwxrwxrwx 1 root root 40 Dec 16 16:33 /opt/microsoft/omsagent/bin/service_control -> /var/vcap/jobs/omsagent/bin/omsagent-ctl
```

* The `is-running` option for `omsagent-ctl` executes `is_process_running` function, which is pulled in from the `utils.sh` again.

```
is_process_running()
{
    PIDFILE=$1
    # Returns 1 if 'omsagent' is running, 0 otherwise
    [ -f $PIDFILE ] || return 0
    ps -p `cat $PIDFILE` | grep -q omsagent
    STATUS=$?

    # Kill PID file if we're not running any longer
    if [ $STATUS -ne 0 ]; then
        rm -f $PIDFILE
        return 0
    else
        return 1
    fi
}
```

* This function pulls the PID from the pidfile and looks for `omsagent`.
* If it's not found, it runs an `rm` on the pidfile, thus explaining the constant restarting of `omsagent`.
* The problem here is the CMD being different, thus breaking `grep -q omsagent`:

```
mysql/b3f6985d-e4c6-45a8-b592-bfa515ebbeee:~# ps -p $(cat /var/vcap/sys/run/omsagent/omsagent.pid)
  PID TTY          TIME CMD
21420 ?        00:00:07 ruby
```

* Two ways to fix this:
    1. Modify the the grep to `grep -q "omsagent\|ruby"` which would check for either.
        - On normal systems the CMD line is `omsagent`, so I'm leaning against this.
    2. Modify the startup script at `/var/vcap/jobs/omsagent/bin/omsagent-ctl`:

    ```
    $RUBY_BIN $OMS_BIN -d $PID_FILE -o $LOG_FILE --no-supervisor -c $OMSAGENT_CONF --user omsagent --group omiusers
    ```

    * If we change the above startup execution and remove the `$RUBY_BIN` it'll stop showing ruby as the `CMD`.
    * There shouldn't be any issues removing the reference to `$RUBY_BIN` since the shebang is identical, and `$OMS_BIN` is executable

* All that being said, going with option 1 and adjusting the `grep -q` would be the safest method.

**Comment by lancefrench** [comment]
Merged will close after we cut a release and test.

**Comment by lancefrench** [comment]
Looks like this was able to install post-merge.  Closing.
